jobs:
  build:
    runs-on: self-hosted
    steps:
    - continue-on-error: true
      name: Checkout code
      uses: actions/checkout@v2
    - continue-on-error: true
      name: Set up JDK 1.8
      uses: actions/setup-java@v1
      with:
        java-version: 1.8
    - continue-on-error: true
      name: Build
      run: './mvnw clean package -DskipTests -T 1C -pl \

        taier-data-develop,\

        taier-common,\

        taier-worker/taier-worker-plugin,\

        taier-datasource/taier-datasource-plugin \

        -am -amd

        '
name: Build With Mvnw
on:
  repository_dispatch:
    types: trigger-ga___build.yml
