jobs:
  deploy:
    name: Deploy to GitHub Pages
    runs-on: self-hosted
    steps:
    - continue-on-error: true
      uses: actions/checkout@v2
    - continue-on-error: true
      uses: actions/setup-node@v2
      with:
        cache: yarn
        cache-dependency-path: website/yarn.lock
        node-version: 14.x
    - continue-on-error: true
      name: Build website
      run: 'yarn install --frozen-lockfile

        yarn build

        '
      working-directory: website
    - continue-on-error: true
      name: Deploy to GitHub Pages
      uses: peaceiris/actions-gh-pages@v3
      with:
        github_token: ${{ secrets.GITHUB_TOKEN }}
        publish_dir: website/build
        user_email: 41898282+github-actions[bot]@users.noreply.github.com
        user_name: github-actions[bot]
name: Deploy to GitHub Pages
on:
  repository_dispatch:
    types: trigger-ga___deploy.yml
