jobs:
  test-deploy:
    name: Test deployment
    runs-on: self-hosted
    steps:
    - continue-on-error: true
      uses: actions/checkout@v2
    - continue-on-error: true
      uses: actions/setup-node@v2
      with:
        cache: yarn
        cache-dependency-path: website/yarn.lock
        node-version: 14.x
    - continue-on-error: true
      name: Test build
      run: 'yarn install --frozen-lockfile

        yarn build'
      working-directory: website
name: Test deployment
on:
  repository_dispatch:
    types: trigger-ga___test-deploy.yml
